cities = [ 
        "boston", 
        "calgary", 
        "charlotte", 
        "chicago", 
        "cincinnati", 
        "cleveland", 
        "columbus", 
        "dallas", 
        "denver", 
        "detroit", 
        "edmonton", 
        "fort-lauderdale",
        "houston", 
        "indianapolis", 
        "kansas-city", 
        "las-vegas", 
        "los-angeles", 
        "miami", 
        "milwaukee", 
        "minneapolis", 
        "montreal", 
        "nashville", 
        "new-orleans", 
        "new-york", 
        "north-jersey",
        "oakland", 
        "orange-county",
        "orlando", 
        "ottawa", 
        "palm-beach", 
        "philadelphia", 
        "phoenix", 
        "pittsburgh", 
        "portland", 
        "raleigh-durham", 
        "sacramento", 
        "salt-lake-city", 
        "san-antonio", 
        "san-diego", 
        "san-francisco", 
        "san-jose", 
        "seattle", 
        "st-louis", 
        "tampa-st-petersburg", 
        "toronto", 
        "vancouver", 
        "washington-dc" 
         ]

nation = ["nation"]

def get_locations():
        return cities + nation